### PR TITLE
Try detecting libffi with pkg-config first, fall-back to plainly use the library

### PR DESCRIPTION
**Pull request by aperezdc**
In some GNU/Linux distributions (example: Arch Linux) the headers for `libffi` are installed in a location which is not in the default compiler search path, and a `libffi.pc` file is provided to allow discovery of the needed build flags using `pkg-config`.

With this fix applied, Meson will try first to find `libffi` using `pkg-config`, and if not found, fall-back to `compiler.find_library()` which will still cover systems which do not install a `.pc` file and provide the `libffi` headers in a standard location.

This fixes the following compilation error:

```
FAILED: xsdump@exe/src_prim-etc.cxx.o
c++  -Ixsdump@exe -I. -I.. -I../src -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -O0 -g -Wall -Wextra -MMD -MQ 'xsdump@exe/src_prim-etc.cxx.o' -MF 'xsdump@exe/src_prim-etc.cxx.o.d' -o 'xsdump@exe/src_prim-etc.cxx.o' -c ../src/prim-etc.cxx
../src/prim-etc.cxx:8:10: fatal error: ffi.h: No such file or directory
#include <ffi.h>
         ^~~~~~~
```

### CODE REVIEW

**Comment by TieDyedDevil** [comment]
I'm looking at the online documentation for Meson's `pkgconfig` module, and it doesn't have the methods you're calling. Furthermore, the example I'm looking at doesn't indicate that the import establishes a global `pkgconfig` variable; rather the import() returns a handle to to the module.

Regardless, the `pkgconfig` module is provided to *create* pkgconfig files, not to use them for lookup.

My best guess as to why this works anyhow is that `pkgconfig.find_library()` resolves to `find_library()` because the `pkgconfig` variable is empty. Unfortunately, that's going to remain a guess since the global `find-library()` function is no longer documented. I can only assume that it must behave differently than the compiler's version, since running it makes a difference for your use case.

Perhaps Meson's `dependency()` function is the correct way to to address the issue you're having with locating the proper paths using pkgconfig...

http://mesonbuild.com/Reference-manual.html#dependency

**Comment by aperezdc** [comment]
@TieDyedDevil: You are indeed right! The `import('pkgconfig')` is _not_ needed, and `dependency()` is what calls `pkg-config` under the hood. I'll update the PR accordingly.

**Comment by aperezdc** [comment]
@TieDyedDevil: I have now updated this to use `dependency()` properly. Could you please take a look? Thanks!

**Comment by TieDyedDevil** [comment]
Thank you.

**Pull request merged**
